"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Import the generateTestsFromFiles function from the playwright-llm-testgenerator package
var index_1 = require("playwright-llm-testgenerator/dist/index");
// Generate tests from files located in the './manualTests' directory
// The generated tests will be saved in the './tests' directory
// The 'codellama' parameter specifies the instruction set or configuration to use this is an optional parameter, If not provided, the default codellama will be used
// The last parameter is the url for ollama server, if not provided, the default url: http://127.0.0.1:11434/api/generate will be used 
(0, index_1.generateTestsFromFiles)('./manualTests', './autogeneratedTests', 'deepseek-coder-v2:latest');
